### ISSUE TITLE
Task 2: Initial UI Design

### ISSUE THREAD

**Issue by aziz-sassi** [mylife-plus/myLife#10]
This Bounty got created from this passed [plan](link) from the [📜 30 days plan Discussion](https://github.com/mylife-plus/myLife/discussions/1)

#Design initial UI wireframes

## Tasks
- [ ] Gather requirements and user stories (2 hours, $30)
- [ ] Sketch wireframes for key screens (4 hours, $60)
- [ ] Review and refine wireframes based on feedback (2 hours, $30)

## Support Material
[Support Material](link)

## Price
120$ (ETA 8h)
