### ISSUE TITLE
Frontend Development - Settings Screen

### ISSUE THREAD

**Issue by aziz-sassi** [mylife-plus/myLife#12]
This Bounty got created from this passed [plan](link) from the [📜 30 days plan Discussion](https://github.com/mylife-plus/myLife/discussions/1)

## Tasks
#Develop UI for setting Screen

- [x] Design and develop UI components for setting Screen (7 hours, $105)

#Develop UI for setting up login PIN

- [ ] Design UI components for PIN setup (3 hours, $45)
- [ ] Implement PIN setup functionality (3 hours, $45)

#Develop UI for setting tags and emojies

- [ ] Design UI components for setting tags and emojies screen (5 hours, $75)
- [ ] Implement PIN setup functionality (6 hours, $90)

#Implement language settings

- [ ] Implement language selection UI (2 hours, $30)
- [ ] Integrate language selection functionality (3 hours, $45)

#Implement security settings for private key and PIN

- [ ] Design security settings UI (4 hours, $60)
- [ ] Implement security features (4 hours, $60)

#Develop UI for enabling dark mode, left-hand mode, and changing font

- [ ] Design UI components for appearance settings (3 hours, $45)
- [ ] Implement appearance settings functionality (3 hours, $45)

#Add data options for backup, upload, and delete data

- [ ] Design UI components for data management (4 hours, $60)
- [ ] Implement data management functionality (4 hours, $60)

## Support Material
[Support Material](link)

## Price
555$ (ETA 37h)
