### ISSUE TITLE
Static UI: Settings Screens

### ISSUE THREAD

**Issue by haythemd** [mylife-plus/myLife#15]
This Bounty got created from this passed [plan](link) from the [📜 30 days plan Discussion](https://github.com/mylife-plus/myLife/discussions/1)

## Tasks
- [ ] Setup Screen -- Settings Screen -- Settings / Contact  (3 Hours ETA - 45$)
- [ ] Settings / Security: all fields excluding activate phone pin should be disabled and greyed out (2 Hours ETA - 30$) 
- [ ] Settings / Memory -- Settings / Data (2 Hour ETA - 30$)
- [ ] Settings / Memory / Emojis: Each Category should be in its own widget. When clicking the edit button a + sign appears to add an emoji. and - sign appears next to each Icon to delete it . Name can be edited also and a Check Icon appears to validate change.   ( 4 Hours ETA - 60$)

The Developer taking this issue is responsible for maintaining proper navigation between all screens.

## Support Material
![image](https://github.com/mylife-plus/myLife/assets/8641466/c15f424d-48a4-4d5b-b605-bd89402c2e06)

[Figma File](https://www.figma.com/file/DQp9RG2Fa6XXsVH0h1D26m/myLife?type=design&node-id=0-1&mode=design&t=0HCd01tyyy2PhpbH-0)

## Price
165$ (ETA 11 Hours)
