### ISSUE TITLE
Static UI: Memory

### ISSUE THREAD

**Issue by haythemd** [mylife-plus/myLife#16]
This Bounty got created from this passed [plan](link) from the [📜 30 days plan Discussion](https://github.com/mylife-plus/myLife/discussions/1)

## Tasks
- [ ] Memory Screen: (5 Hours ETA - 60$)
              Make sure to wrap a single Memory Widget into a component.  
- [ ] Memory / New Memory: (5 Hours ETA - 75$)
           - Clicking Date and Time should pop a DateTime calendar. 
           - Clicking location Prompts to choose to enter location manually ( Lat/Lng) or Get Location Current Location. (Widget to be provided)
           - Clicking contacts pops a list of contacts
           - Clicking Emojis pops a list of emojis 

- [ ] Memory Filter -- Memory Filter / Contact -- Memory Filter / Emojis: (4 Hours ETA - 60$) 

Implement Filter Screen with all relative Screens to it.

Notes: The developer is responsible for developing the navigation system between pages

## Support Material

![image](https://github.com/mylife-plus/myLife/assets/8641466/83e5cf9d-8aea-40e0-aba3-244b6445442e)

[Figma Link](https://www.figma.com/file/DQp9RG2Fa6XXsVH0h1D26m/myLife?type=design&node-id=0-1&mode=design&t=0HCd01tyyy2PhpbH-0)

## Price
210$ (ETA 14 Hours)
