### ISSUE TITLE
Logic: Memory Screen

### ISSUE THREAD

**Issue by haythemd** [mylife-plus/myLife#22]
This Bounty got created from this passed [plan](link) from the [📜 30 days plan Discussion](https://github.com/mylife-plus/myLife/discussions/1)

## Tasks
- [ ] Implement CRUD functionalities for Memories (Wrap the CRUDs in a service class) (5 Hours ETA )
- [ ] Implement createMemory in Create Memory Screen (ETA 3 Hours)
( Use the content attribute to store a Json String containing information about content, example:
{
   [
      {
         type: enum [text, image, audio, video]
         source: String
      }
   ]
}

Provide a list of content, Type and Source, for text it would be a normal Text String, for Others it would be a path for the file 

- [ ] READ: Implement getAllMemories inside the View Memories screen (ETA 3 Hours)
- [ ] UPDATE: Implement editMemory ( Use the Add Memory Screen with default attributes as placeholders) (ETA 3 Hours)
- [ ] DELETE: Implement deleteMemory inside the View Memories Screen (ETA 1 Hour)
- [ ] READ: Implement getMemory inside Memory / Full Screen (ETA 2 Hours)
- [ ] ADD: Implement addMemory inside the Add Memory Screen (ETA 4 Hours)

## Support Material
![image](https://github.com/mylife-plus/myLife/assets/8641466/9cdf7bb3-c8b3-4a00-91e5-d592b9b5fd10)

## Price
195$ (ETA 13h)
