### ISSUE TITLE
governance structure

### ISSUE THREAD

**Issue by MouyouMoos** [mylife-plus/myLife#27]
This Bounty got created from this passed [plan](https://github.com/mylife-plus/myLife/discussions/1#discussioncomment-9232325) from the [📜 plan Discussion](https://github.com/mylife-plus/myLife/discussions/1)

## Tasks
- [x] brainstorm/research a fair and decentralized governance structure where stakeholders of the project are in control (ETA 5h)
- [x] visualize this structure in a figma file (ETA 3h)
- [x] create new discussions in the repository which explains in detail how the governance structure works (ETA 5h)

## Support Material
[myLife DAO](https://www.figma.com/board/aq4b1niEivXWgBfENSppyu/myLife-Dao?node-id=0%3A1&t=UYF716T3oEo4vsAJ-1)

## Price
195$ (ETA 13h)
